# Generated by Django 3.2.4 on 2021-06-19 20:46

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('regular', 'Regular'), ('square', 'Square')], default='regular', max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('exra-large', 'Extra-Large'), ('massive', 'Massive')], default=None, max_length=10)),
                ('toppings', multiselectfield.db.fields.MultiSelectField(choices=[('pepperoni', 'Pepperoni'), ('mushroom', 'Mushrooms'), ('onions', 'Onions'), ('sausage', 'Sausage'), ('bacon', 'Bacon'), ('extra cheese', 'Extra cheese'), ('black olives', 'Black olives'), ('tomato', 'Tomato'), ('capsicum', 'Capsicum')], default=1, max_length=81)),
            ],
        ),
    ]
